---
- hosts: all
  become: true

  tasks:
  
    - name: Install packages for Docker
      yum:
        name:
          - install
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - yum-utils
          - lvm2
          - lsb-release
        state: present
        
    - name: Curl gpg
      shell: "curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg"

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
      become: yes

    - name: Install Docker
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
      become: yes

    - name: Install docker-compose
      get_url: 
        url : https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-x86_64
        dest: /usr/bin/docker-compose
        mode: 'u+x,g+x'  
      become: yes

    - name: Enable docker and add user to docker group
      shell: |
        usermod -aG docker $USER
        chown $USER /var/run/docker.sock
        systemctl enable docker
      args:
        executable: /bin/bash

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes
      
    - name: Create directory docker
      file:
        path: /data/docker
        state: directory
        owner: jenkins
        group: jenkins
        mode: 0755

    - name: Create directory for database
      file:
        path: /data/docker/db
        state: directory
        owner: jenkins
        group: jenkins
        mode: 0755

    - name: Create directory for wp
      file:
        path: /data/docker/html
        state: directory
        owner: jenkins
        group: jenkins
        mode: 0755

    - name: Copy docker-compose 
      copy:
        src: /var/lib/jenkins/workspace/001_docker_install/project_sa/docker/docker-compose.yml
        dest: /data/docker
        owner: jenkins
        group: jenkins
        mode: 0644

    - name: Run docker-compose
      shell: docker-compose up -d
      args:
        chdir: /data/docker
