---
- hosts: all
  become: true
  tasks:

  - name: Stop docker
    shell: "docker stop $(docker ps -a -q)"
    failed_when: false
    args:
      chdir: /data/docker

  - name: Remove docker images
    shell: "docker rm $(docker ps -a -q)"
    failed_when: false
    args:
      chdir: /data/docker

  - name: Run docker-compose up
    shell: docker-compose -f /data/docker/docker-compose_upd.yml up -d
    args:
      chdir: /data/docker

  - name: Pause 10
    pause:
      seconds: 10

  - name: Curl and check output (Handle the error)
    block:
      - name: Curl content
        uri:
          url: "http://localhost:8000"
          return_content: yes
        register: content
        failed_when: true
#        failed_when: "'WordPress' not in content.content"
#      - name: Print content
#        debug:
#          msg: "{{ content }}"

      - name: mv -f upd to stable
        shell: mv -f docker-compose_upd.yml docker-compose.yml
        args:
          chdir: /data/docker
 
    rescue:
#      - name: Send to Slack
#        local_action:
#          module: slack
#          token: XXX/XXX
#          msg: "Upgrade failed, try rollback"
#          channel: "#ansible_notification"
#          username: "Ansible"
        
      - name: Run upd docker-compose
        shell: docker-compose -f docker-compose_upd.yml down
        args:
          chdir: /data/docker

      - name: remove image
        shell: "docker rmi -f $(docker images -a -q)"
        failed_when: false

      - name: Remove bad docker file
        shell: rm -f docker-compose_upd.yml
        args:
          chdir: /data/docker

      - name: Run old docker file
        shell: docker-compose -f docker-compose.yml up -d
        args:
          chdir: /data/docker

      - name: Pause 10
        pause:
          seconds: 10

      - name: Curl and check output
        block:
          - name: Curl content
            uri:
              url: "http://localhost:8000"
              return_content: yes
            register: content
#            failed_when: "'WordPress' not in content.content"
#          - name: Print content
#            debug:
#              msg: "{{ content }}"

#        rescue:
#          - name: Send crash message
#            local_action:
#              module: slack
#              token: XXX/XXX
#              msg: "Rollback Crash"
#              channel: "#ansible_notification"
#              username: "jenkins_build"
#              parse: 'full'
