---
- hosts: all
  become: true

- name: Stop docker
  shell: |
    docker stop wordpress
    docker stop mysql
  args:
    chdir: /data/docker

- name: Remove docker images
  shell: |
    docker rm wordpress
    docker rm mysql
  args:
    chdir: /data/docker

- name: Run docker-compose up
  shell: docker-compose -f docker-compose_upd.yaml up -d
  args:
    chdir: /data/docker

- name: Pause 10
  pause:
    seconds: 10

- name: Curl and check output (Handle the error)
  block:
    - name: Curl content
      uri:
        url: "http://localhost:8000"
        return_content: yes
      register: content
      failed_when: "'WordPress' not in content.content"
    - name: Print content
      debug:
        msg: "{{ content }}"
 
  rescue:
    - name: Send to Slack
      local_action:
        module: slack
        token: XXX/XXX
        msg: "Upgrade failed, try rollback"
        channel: "#ansible_notification"
        username: "Ansible"
        
    - name: joomla_rollback

